#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # Change the default shell to be zsh
  sudo sh -c "echo $(which zsh) >> /etc/shells"
  $ chsh -s $(which zsh)

  # Enable key repeat on programming apps
  defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
fi

